---
- name: install anaconda-3-2019.3 on Linux
  hosts: all
  gather_facts: true
  vars:
    file_path: /tmp/Anaconda3-2019.03-Linux-x86_64.sh
  tasks:
    - name: Install bzip2
      yum:
        name: bzip2
        state: present
      become: true
      become_user: root


    - name: check anaconda is persent or not
      stat:
        path: /home/anaconda_3
      register: anaconda3


    - name: download anaconda
      get_url:
        url: https://repo.anaconda.com/archive/Anaconda3-2019.03-Linux-x86_64.sh
        dest: "{{ file_path }}"
        checksum: sha256:45c851b7497cc14d5ca060064394569f724b67d9b5f98a926ed49b834a6bb73a
        force: true
        validate_certs: false
      delegate_to: localhost

    - name: copy anaconda-3-2019.3 to remote host
      copy:
        src: "{{ file_path }}"
        dest: "{{ file_path }}"

    - name: Install anaconda-3-2019.3 to remote host
      command: bash "{{ file_path}}" -b -p /home/anaconda_3
      become: true
      become_user: root
      when: not anaconda3.stat.exists

    - name: update bashrc for anaconda_3
      lineinfile:
        path: ~/.bashrc
        line: 'export PATH="/home/anaconda_3/bin:$PATH"'
      become: true
      become_user: root
