---
- name: install nodejs on Linux
  hosts: all
  gather_facts: true
  tasks:
    - name: Download repos
      get_url:
        url: "{{ item }}"
        dest: /tmp/
        validate_certs: false
      delegate_to: localhost
      with_items:
        - https://dl.yarnpkg.com/rpm/yarn.repo
        - https://rpm.nodesource.com/setup_10.x

    - name: Enable yarn repo
      copy:
        src: /tmp/yarn.repo
        dest: /etc/yum.repos.d/
        owner: root
        group: root
      become: true

    - name: copy nodejs file to remote
      copy:
        src: /tmp/setup_10.x
        dest: /tmp/setup_10.x
      become: true
      become_user: root

    - name: Install yarn
      yum:
        name: yarn
        state: present
      become: true
      become_user: root

    - name: enable nodejs repo
      command: bash /tmp/setup_10.x
      become: true
      become_user: root
